### ISSUE TITLE
API: Login failed with newest git version ( 6f42fec6715bfa)

### ISSUE THREAD

**Issue by Nidhoegger** [Sude-/lgogdownloader#123] opened 2017-09-08 16:58 UTC
When I try to download my GOG games with:
`lgogdownloader --language en --platform l --game all --download --verbose`
I get prompted for my Mail and PW. After entering, I get:

```
* Found bundle for host api.gog.com: 0x557421f51dd0 [can pipeline]
* Re-using existing connection! (#0) with host api.gog.com
* Connected to api.gog.com (92.122.29.8) port 443 (#0)
> GET /oauth/initialize/?oauth_consumer_key=xxxxxxxxxx&oauth_nonce=xxxxxxxxxxx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=xxxxxxxxxx&oauth_version=1.0&oauth_signature=xxxxxxxxxxxxxx HTTP/1.1
Host: api.gog.com
Accept: */*

* The requested URL returned error: 500 Internal Server Error
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
API: Login failed
```

Is there any solution?

**Comment by Sude-** [comment] 2017-09-08 20:22
This seems to be the same issue as https://github.com/Sude-/lgogdownloader/issues/122
It's a server side issue with GOG OAuth API.
There are some issues reported by users of official GOG Downloader (for example: https://www.gog.com/forum/general/gogs_old_downloader_issues/page1) and I suspect that they are also caused by the same server side issue
The only thing that can be done at the moment is to report this issue to GOG support and hope they will fix the issue.
I already reported this to GOG support but I haven't heard back from them yet.

I've started working on code to use Galaxy API for getting all the necessary product info.
Sadly the Galaxy API has some design principles that makes getting some game details slightly harder.

Currently the code that I'm testing takes a lot longer to get the details and some features are not working at all. These features require a lot of changes and possibly a complete rewrite of some functions that isn't compatible with current behavior.
For example ```--download-file``` option is not currently working using the Galaxy code and it looks like I won't be able to make it backwards compatible with older versions with all the changes it needs.

**Comment by Nidhoegger** [comment] 2017-09-10 09:52
Thank you for the info and thank you for your work. I will contact GOG then :)

**Comment by Sude-** [comment] 2017-09-13 13:54
706158d makes the downloader use Galaxy API for getting game details and should allow most features to work without valid API login

**Comment by christiandreher** [comment] 2017-09-14 09:38
But downloads won't work, right? I mean, thats what the login is for, isn't it?

**Comment by Sude-** [comment] 2017-09-14 10:13
> But downloads won't work, right? I mean, thats what the login is for, isn't it?

Downloads should work because I changed the downloader to get download links using Galaxy API.

There are couple of things that still use the old API and don't work without valid login for it.
```--download-file``` uses the old API. It prints error message and exits if API isn't logged in. I'm trying to figure out if I can change it to Galaxy API without breaking tools that rely on that functionality.
```--update-check``` also uses the old API for getting some details.

**Comment by Nidhoegger** [comment] 2017-09-17 10:24
Thank you for your work. I dont know if its your changes or some changes GOG did on their servers, but since today, the API Login is also successful. I have checked out 2d70bdfacbd1dc9b51e9c00409b4b97b381e71e9

**Comment by christiandreher** [comment] 2017-09-17 19:17
I can confirm that it works now, too. @Sude- you can consider closing the related issues in this case. Thanks everyone :)

**Closed** 2017-09-18 06:12 UTC

**Comment by diamond-lizard** [comment] 2019-10-03 16:16
This issue is still happening for me with lgogdownloader 3.5 on Gentoo Linux:

```
> lgogdownloader --login
Email: myemail@example.com
Password:
HTTP: Login successful
Galaxy: Login successful
API: Login failed (some features may not work)
```

**Comment by joyfullbufallo** [comment] 2020-08-11 10:04
@diamond-lizard I'm not sure you are still looking for a solution but i found a newer version 3.7 and it fixed this problem for me.
https://sites.google.com/site/gogdownloader/
