### ISSUE TITLE
Cant Login.

### ISSUE THREAD

**Issue by nogarth** [Sude-/lgogdownloader#12] opened 2014-04-13 18:45 UTC
there seems to be an issue that has appeared today. when i try to log in now is says

HTTP response code said error
- Line 1, Column 1
  Syntax error: value, object or array expected.
  HTTP: Login failed

this was happening before when i was trying to update my collection with lgogdownloader as well.

i am using the current git version and been working all week till now. unsure if gog have changed something there end.

**Comment by braedenjc** [comment] 2015-06-18 00:28
I have recently encountered a problem where I cannot login to GOG.com, and am recieving something about certificate errors.

Below is the verbose output:

*   Trying 23.208.232.84...
* Connected to api.gog.com (23.208.232.84) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
* Rebuilt URL to: oauth_nonce=redacted for this post
oauth_consumer_key=redacted for this post
oauth_signature_method=redacted for this post
oauth_token=redacted for this post
oauth_signature= redacted for this post
* Could not resolve host: //Just references the Oauth stuff above.
* Closing connection 1
Email: insertloginhere@lol.com
Password: 
*   Trying 23.208.232.84...
* Connected to www.gog.com (23.208.232.84) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
* Hostname www.gog.com was found in DNS cache
*   Trying 23.208.232.84...
* Connected to www.gog.com (23.208.232.84) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 1
* Hostname www.gog.com was found in DNS cache
*   Trying 23.208.232.84...
* Connected to www.gog.com (23.208.232.84) port 443 (#2)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 2
* Hostname www.gog.com was found in DNS cache
*   Trying 23.208.232.84...
* Connected to www.gog.com (23.208.232.84) port 443 (#3)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 3
Peer certificate cannot be authenticated with given CA certificates
Failed to find url for login form
Failed to get login token
HTTP: Login failed


To try to remedy, I have deleted the cookie file in my ~\.config\lgogdownloader. Sadly, this didn't work. 

I then tried to run the program as root to determine if I had a weird certificate problem on my computer. This did not work either. 

Is there anything else I can try to fix this?

**Comment by sleeksorrow** [comment] 2015-07-30 08:34
Can't login either. Tried for some weeks now with no change, so i guess there is no temporary server side issue. Can login fine with browser.

Made a Debug build and have the verbose log here: http://pastebin.com/SuE3TwTQ

It once worked fine on another machine and if I copy the cookies around I can use it.

**Comment by Sude-** [comment] 2015-08-12 13:33
> Can't login either. Tried for some weeks now with no change, so i guess there is no temporary server side issue. Can login fine with browser.
> 
> Made a Debug build and have the verbose log here: http://pastebin.com/SuE3TwTQ
> 
> It once worked fine on another machine and if I copy the cookies around I can use it.

This seems to be caused by reCAPTCHA on the login form (https://github.com/Sude-/lgogdownloader/issues/59)

**Comment by jschuck** [comment] 2015-08-12 17:29
For what it's worth I'm using LGOGDownloader 2.24. I just tested it with the one made from the AUR package on my european based arch install and my self-compiled one on my american based digital ocean debian install. Both logged in perfectly and worked as expected.

**Comment by sleeksorrow** [comment] 2015-08-12 18:06
After reading that I just retested it using the latest git revision and it worked for me now, too. Of course this way I cannot tell if that was fixed on server side or client side.

**Comment by ProfessorKaos64** [comment] 2016-08-31 15:24
See #77. This should be considered closed. I did contact GOG Support about the reCAPTCHA part. They noted 1 hour is the timeout if you don't hammer the API with more login attempts. In extreme cases, this can take up to 24 hours. Might be useful to note this in the readme or somewhere.

**Closed** 2017-06-07 08:55 UTC
